# Generated by Django 4.1.1 on 2022-09-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_listing_buyer_alter_listing_date_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unisex')], default='U', max_length=1),
        ),
    ]
