# Generated by Django 4.1.1 on 2022-09-19 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_alter_listing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='gender',
            field=models.CharField(choices=[('F', 'FEMALE'), ('M', 'MALE'), ('U', 'UNISEX')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='listing',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'X-Large')], default='S', max_length=3),
        ),
    ]
