# Generated by Django 4.1.1 on 2022-09-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_listing_gender_alter_listing_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date_sold',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
